In [1]:
import numpy as np

muy importante observen que:

“producto interno” toma dos vectores y regresa un escalar.
“producto externo” toma dos vectores y devuelve una matriz.(este no se menciono pero vale la pena lo revisen) 

matriz * vector
https://static.platzi.com/media/user_upload/1-bc75dc14-7def-4dfc-aea7-e6f5d36e512f.jpg
https://static.platzi.com/media/user_upload/2-8215a7ff-da28-45a4-bd0f-54280f0647da.jpg

en el producto interno 
multiplica el 2 por todos los a11,a21,a31, y el 3 por cada a12,a22,a32

y luego suma a11 + a12, a21 + a22, a31+ a32

In [2]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
A = matriz * vector # multiplicacion simple

In [4]:
B = matriz.dot(vector)  # producto interno

In [5]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [6]:
print(B)

[ 8 18 28]


In [7]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]


In [8]:
D = np.array([[2],[2],[2]])

In [9]:
print(D)

[[2]
 [2]
 [2]]
