In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [4]:
A = matriz.T + vector

In [5]:
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [6]:
C = matriz + 42

In [7]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [8]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]


La regla a entender aqui es que broadcast depene del shape del elemento y aplica de la siguiente manera

si se suma un escalar siempre hay broadcasting si se suma un vector importa el numero de columnas sean iguales en ambos elementos. si es una matrix importa el numero de filas y columnas sean iguales en ambos elementos.

Explicado en forma de shape

una matrix de shape (2, 4) puede sumarse con un vector de shape (4,) o shape (1,) un tensor de shape (6, 2, 3) se puede sumar un vector de shape (3,) o (1,) y una matrix de shape (2, 3)

In [ ]:
https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png